#!/bin/bash
## Copyright (c) 2012, 2013 Aldebaran Robotics. All rights reserved.
## Use of this source code is governed by a BSD-style license that can be
## found in the COPYING file.
##


# find qibuild root directory
if readlink -f . >/dev/null 2>/dev/null ; then
    qibuild_dir=$(dirname "$(readlink -f ${0} 2>/dev/null)")
else
    qibuild_dir=$(dirname "${0}")
    qibuild_dir=$PWD/${this_dir}
fi

# Generate sourceme.sh
cat > ${qibuild_dir}/sourceme.sh << EOL
#!/bin/bash
# Autogenerated by generate-sourceme.sh
# Source this file to use qibuild from its source dir

# find qibuild root directory
qibuild_dir=${qibuild_dir}

# set path
export PATH="\${qibuild_dir}/python/bin:\$PATH"
export PYTHONPATH="\${qibuild_dir}/python:\$PYTHONPATH"

# define aliases
alias qc="qibuild configure"
alias qm="qibuild make"
alias qi="qibuild install"
alias qd="qibuild deploy"
alias qo="qibuild open"

# helper functions
function qicd {
  p=\$(python \${qibuild_dir}/python/qicd.py \$1)
  if [[ \$? -ne 0 ]]; then
    return
  fi
  cd \${p}
}

function q {
  qibuild configure \$@ && qibuild make \$@
}

EOL

echo "qibuild sources found in ${qibuild_dir}"
echo
echo "now patch your ~/.profile with"
echo
cat <<EOF
# Autogenerated by ./install-qibuild.sh
source ${qibuild_dir}/sourceme.sh
EOF
