#!/bin/sh
## Copyright (c) 2012, 2013 Aldebaran Robotics. All rights reserved.
## Use of this source code is governed by a BSD-style license that can be
## found in the COPYING file.
##


# find qibuild root directory
if readlink -f . >/dev/null 2>/dev/null ; then
    qibuild_dir=$(dirname "$(readlink -f ${0} 2>/dev/null)")
else
    qibuild_dir=$(dirname "${0}")
    qibuild_dir=$PWD/${this_dir}
fi

echo "qibuild sources found in ${qibuild_dir}"
echo
echo "now patch your ~/.profile with"
echo
cat <<EOF
# Autogenerated by ./install-qibuild.sh
source ${qibuild_dir}/sourceme.sh
EOF
