"""Generate the use_qibuild.cmake file """

import os
import qibuild


USE_QIBUILD_TEMPLATE="""# Autogenerated file. Do NOT edit.
set(QI_BUILD_ROOT "%s")
list(APPEND CMAKE_MODULE_PATH ${QI_BUILD_ROOT}/cmake)

include(qibuild/general)
"""


def configure_parser(parser):
    """Configure parser for this action """
    qibuild.shell.toc_parser(parser)
    parser.add_argument("output", metavar="OUTPUT",
        help="where to generate the file")

def do(args):
    """Main entry point"""
    # Right now, qibuild is a toc project, but
    # this will not be the case very long :)
    toc = qibuild.toc.toc_open(args)
    qibuild_proj = toc.get_project("qibuild")
    qibuild_src = qibuild_proj.get_src_dir()
    qibuild_src = qibuild.toc.path.to_posix_path(qibuild_src)
    output = os.path.join(args.output, "use_qibuild.cmake")
    with open(output, "w") as output_file:
        output_file.write(USE_QIBUILD_TEMPLATE % qibuild_src)

if __name__ == "__main__" :
    import sys
    qibuild.shell.sub_command_main(sys.modules[__name__])

