"""Configure a project

"""

import os
import logging
import qibuild

# def generate_find_deps(args, toc, project):
#     """Generate the find_deps.cmake for the given project

#     """
#     build_dir = project.cmake.get_build_dir()
#     if not os.path.exists(build_dir):
#         os.makedirs(build_dir)
#     dep_sdk_dirs = list()
#     deps = toc.resolve_deps([project])
#     deps.remove(project)
#     for dep in deps:
#         dep_build_dir = dep.cmake.get_build_dir()
#         dep_sdk_dir = os.path.join(dep_build_dir, "sdk")
#         dep_sdk_dirs.append(dep_sdk_dir)

#     to_write = "#Autogenerated file. Do NOT edit.\n"
#     for dep_sdk_dir in dep_sdk_dirs:
#         to_write += """list(APPEND CMAKE_PREFIX_PATH "%s")\n""" % \
#             qibuild.toc.path.to_posix_path(dep_sdk_dir)

#     output_path = os.path.join(build_dir, "find_deps.cmake")
#     with open(output_path, "w") as output_file:
#         output_file.write(to_write)

#     logger = logging.getLogger(__name__)
#     logger.debug("Wrote %s to %s", to_write, output_path)


def configure_parser(parser):
    """Configure parser for this action"""
    qibuild.shell.toc_parser(parser)
    qibuild.shell.build_parser(parser)
    qibuild.shell.project_parser(parser)
    group = parser.add_argument_group("cmake arguments")
    group.add_argument("-D", dest="cmake_flags", action="append",
        help="additional cmake flags")


def do(args):
    """Main entry point"""
    logger   = logging.getLogger(__name__)
    toc      = qibuild.toc.toc_open(args.toc_work_tree, use_env=True)

    print ""
    print "buildable projects:"
    for p,v in toc.buildable_projects.iteritems():
        print " -", p, ":", toc.configstore.get("project", p, "depends")

    projects = qibuild.toc.get_projects_from_args(toc, args)

    print ""
    print "project wanted:"
    for project in projects:
        print " -", project

    tobuild   = []
    toinstall = []
    for project in projects:
        if project in toc.buildable_projects.keys():
            tobuild.append(project)
        else:
            toinstall.append(project)

    print ""
    print "project to configure:"
    for project in tobuild:
            print " -", project

    print ""
    print "project you should install in your system:"
    for project in toinstall:
            print " -", project

    #projects = qibuild.shell.get_projects(args, toc, args.projects)

    # Set build configurations
    #qibuild.shell.buildaction.set_build_configs(args, toc, projects)

    #for project in projects:
    #    generate_find_deps(args, toc, project)

    # Call CMake for every dep:
    # for project in projects:
    #     logger.info("Configuring [%s]", project.name)
    #     #qibuild.shell.buildaction.run_cmake(args, project)

if __name__ == "__main__":
    import sys
    qibuild.shell.sub_command_main(sys.modules[__name__])


