get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
include("${_ROOT_DIR}/boostutils.cmake")
boost_flib("timer")
set(_deps)
list(APPEND _deps BOOST_CHRONO)
qi_set_global(BOOST_TIMER_DEPENDS ${_deps})
