## Copyright (C) 2011 Aldebaran Robotics

clean(OPENCV)
fpath(OPENCV opencv/cv.h ${_in_system} )
flib(OPENCV OPTIMIZED NAMES cv      cv200      )
flib(OPENCV DEBUG     NAMES cv      cv200d     )
flib(OPENCV OPTIMIZED NAMES cvaux   cvaux200   )
flib(OPENCV DEBUG     NAMES cvaux   cvaux200d  )
flib(OPENCV OPTIMIZED NAMES cxcore  cxcore200  )
flib(OPENCV DEBUG     NAMES cxcore  cxcore200d )
flib(OPENCV OPTIMIZED NAMES highgui highgui200 )
flib(OPENCV DEBUG     NAMES highgui highgui200d)
flib(OPENCV OPTIMIZED NAMES ml      ml200d     )
flib(OPENCV DEBUG     NAMES ml      ml200      )
export_lib(OPENCV)
