##
## Author(s):
##  - Cedric <gestes@aldebaran-robotics.com>
##
## Copyright (C) 2010 Aldebaran Robotics
##

include(ExternalProject)

#! QiBuild Autotools
# ==================
# Cedric GESTES <gestes@aldebaran-robotics.com>

#!
# This modules allow building external autotools projects
# install rules are autogenerated.

#! compile an autotols based project
# \arg:name the name of the project
# \arg:url the url of the project to download. (could start with http:// or file://)
# \param:MD5 the md5 of the specified file
# \group:PATCH a list of patch to apply before building
# \group:CONFIGURE_OPTIONS optional configure options
# \group:INSTALL_OPTIONS arguments to pass to the install command
function(qi_build_autotools name url)
  cmake_parse_arguments(ARGS "" "MD5" "PATCH;INSTALL_OPTIONS;CONFIGURE_OPTIONS" ${ARGN})

  set(options)
  #enable cross-compilation
  if (QI_AUTOTOOLS_HOST)
    list(APPEND options "--host=${QI_AUTOTOOLS_HOST}")
  endif()

  list(APPEND options "${ARGS_CONFIGURE_OPTIONS}")

  set(patchs_cmd)
  foreach(p ${ARGS_PATCH})
    list(APPEND patchs_cmd "patch" "-p1" "<" "${p}" ";")
  endforeach()

  ExternalProject_Add(${name}
    URL               "${url}"
    URL_MD5           "${ARGS_MD5}"
    PREFIX            "${name}"
    BUILD_IN_SOURCE   1
    PATCH_COMMAND     "${patchs_cmd}"
    CONFIGURE_COMMAND "./configure" --prefix=/. ${options}
    INSTALL_COMMAND   "DESTDIR=${QI_SDK_DIR}" make install ${ARGS_INSTALL_OPTIONS}
    )

  #generate install rules for the project
  qi_install_autotools_project()
endfunction()


#! install all files related to an autotools like project.
function(qi_install_autotools_project)
  get_filename_component(_THIS_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
  set(SOURCE_FOLDER "${QI_SDK_DIR}")
  set(QI_BUILD_DIR  "${QI_BUILD_ROOT_DIR}")
  configure_file("${QI_TEMPLATE_DIR}/install_autotools.cmake"
                 "${CMAKE_CURRENT_BINARY_DIR}/install_autotools.cmake"
                 @ONLY)
  install(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/install_autotools.cmake")
endfunction()
