""" Helper script to build qibuild documentation without
access to the aldebaran templates or using qidoc

"""

import os
import sys

import qisys.command
import qisys.sh
import sphinx

def generate_conf_py(source_dir, build_dir):
    """ Generate a suitable conf.py """
    conf_in_py = os.path.join(source_dir, "conf.in.py")
    with open(conf_in_py, "r") as fp:
        contents = fp.read()
    header = """\
# Generated by build-doc.py. Do not edit
import sys
import os

source_suffix = '.rst'
master_doc = 'index'

extensions = ["sphinx.ext.todo"]
"""
    contents = header + contents
    out_conf_py = os.path.join(build_dir, "conf.py")
    with open(out_conf_py, "w") as fp:
        fp.write(contents)

def call_gen_cmake_doc(source_dir):
    gen_cmake_doc = os.path.join(source_dir, "..", "tools", "gen_cmake_doc.py")
    cmd = [sys.executable, gen_cmake_doc, source_dir]
    qisys.command.call(cmd)


def call_sphinx(source_dir, build_dir):
    cmd = [sys.executable, "-c", build_dir]
    cmd.extend(("-b", "html"))
    cmd.append(source_dir)
    cmd.append(build_dir)
    sphinx.main(argv=cmd)


def main():
    this_dir = os.path.dirname(__file__)
    build_dir = os.path.join(this_dir, "build-doc")
    qisys.sh.mkdir(build_dir)
    source_dir = os.path.join(this_dir, "source")
    generate_conf_py(source_dir, build_dir)
    call_gen_cmake_doc(source_dir)
    call_sphinx(source_dir, build_dir)

if __name__ == "__main__":
    main()
