#!/bin/bash -e
## Copyright (C) 2011 Aldebaran Robotics

# Generate a .tar.gz containing
# qibuild/python/qibuild/test/{world, hello}

# Usage: generate_example_archive /path/to/qibuild /path/to/build

function generate_example_archive {
  qi_root="$1"
  dest_dir="$2"
  mkdir -p "$dest_dir/qi-examples"
  cp -r ${qi_root}/python/qibuild/test/{world,hello} "$dest_dir/qi-examples"
  cp -r ${qi_root}/doc/foobar "$dest_dir/foobar"
  pushd $2
  tar cfz qi-examples.tar.gz qi-examples
  tar cfz foobar.tar.gz foobar
  popd

}


if [ $# -ne 2 ]; then
  echo "usage: $0 /path/to/qibuild /path/to/build"
  exit 2
fi

generate_example_archive $1 $2



