set(CMAKE_CROSSCOMPILING ON)

include(CMakeForceCompiler)
CMAKE_FORCE_C_COMPILER("${CMAKE_CURRENT_LIST_DIR}/fake-gcc" GNU)
CMAKE_FORCE_CXX_COMPILER("${CMAKE_CURRENT_LIST_DIR}/fake-g++" GNU)
set(CMAKE_LINKER  "${CMAKE_CURRENT_LIST_DIR}/fake-ld"     CACHE FILEPATH "" FORCE)
set(CMAKE_AR      "${CMAKE_CURRENT_LIST_DIR}/fake-ar"     CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB  "${CMAKE_CURRENT_LIST_DIR}/fake-ranlib" CACHE FILEPATH "" FORCE)
