/** \file test.cpp
 * This code is automatically generated by qibuild.
 * If you build/use this test, modify CMakeLists.txt
 */

#include <iostream>
#include "@module_name@.h"
#include <assert.h>
#include <alcommon/albroker.h>

int main(void) {
  // If your naoqi is running another host, 
  // Please modify following values
  std::string pip = "localhost"; 
  int16_t pport   = 9559;


  boost::shared_ptr<AL::ALBroker> broker;
  try { 
    broker = AL::ALBroker::createBroker("testbroker",
					"0.0.0.0",
					0,
					pip,
					pport,
					0
					);
  } catch (...) {
    std::cerr << "Fail to connect broker [" << pip << ":" << pport << std::endl;
    return 1;
  }

  
  @module_name@ newModule(broker, "@module_name@");
  
  std::cout << "Starting Test [echo]" << std::endl;
  assert(newModule.echo(AL::ALValue(12345)) == AL::ALValue(12345));
  assert(newModule.echo(AL::ALValue("foo")) == AL::ALValue("foo"));
  assert(newModule.echo(AL::ALValue(3.1416)) == AL::ALValue(3.1416));

  std::cout << "OK" << std::endl;;
  return 0;
}
